#!/usr/bin/env bash -e
# No -x as I don't want to see the command output

printf "\n--- status ---\n"
git s
printf "\n--- starting difftool ---\n"
git d --staged
printf "\n--- ready to commit? ---\n"
npx git-cz
