#!/usr/bin/env bash -xe

# 📖 https://git-scm.com/book/en/v2/Git-Basics-Git-Aliases

# Convenience alias for reviewing a branch before a Merge/Pull Request
# It ignores contents of the `Pods` directory, which is super convenient for my iOS developement workflow
git config --global alias.review '!f(){ master_hash=$(git merge-base upstream/master HEAD); git difftool $master_hash HEAD -- '\'':!Pods'\''; };f'

# List all the files that changed on the branch
git config --global alias.reviewll '!f(){ master_hash=$(git merge-base upstream/master HEAD); git diff --name-only $master_hash HEAD -- '\'':!Pods'\''; };f'

# Shortcut for status
git config --global alias.s 'status --short --branch'

# Shortcut for commit workflow
git config --global alias.c 'commit-workflow'

# Shortcut for log
git config --global alias.l 'log --oneline'

# Shortcut for difftool
git config --global alias.d 'difftool HEAD'

# Shortcut for branch
git config --global alias.br 'branch --sort=committerdate -vv'

# Show all logs relative to the commit... and as such, show the MR number
git config --global alias.mr '!f() { local b=${2-master}; git log --merges $1..$b | tail; }; f'

# Go back on master and catchup on the upstream (ie pull upstream and push origin)
git config --global alias.cu 'catchup'

# Shortcut for interactive rebase from upstream
git config --global alias.rum 'rebase -i upstream/master'

# Shortcut removing branches that are safe to delete
# ie everything that is not the current branch or master
git config --global alias.cleanup '!git branch --merged | grep -v "\\*\\|master" | xargs -n 1 git branch -d'
